name: Mirror Bot CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  DO_image: registry.digitalocean.com/reddit-lemmy-mirror-bot/mirror-script:latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Make dotenv file
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_LEMMY_USERNAME: ${{ secrets.LEMMY_USERNAME }}
        envkey_LEMMY_PASSWORD: ${{ secrets.LEMMY_PASSWORD }}
        envkey_LEMMY_INSTANCE: ${{ secrets.LEMMY_INSTANCE }}
        envkey_LEMMY_COMMUNITY: ${{ secrets.LEMMY_COMMUNITY }}
        envkey_REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        envkey_REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        envkey_REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        envkey_REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
        envkey_REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
        envkey_REDDIT_SUBREDDIT: ${{ secrets.REDDIT_SUBREDDIT }}
        envkey_DIGITAL_OCEAN_TOKEN: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        envkey_FILESTACK_API_KEY: ${{ secrets.FILESTACK_API_KEY }}
        envkey_FILESTACK_APP_SECRET: ${{ secrets.FILESTACK_APP_SECRET }}
        envkey_FILESTACK_HANDLE_REFRESH: ${{ secrets.FILESTACK_HANDLE_REFRESH }}
        envkey_FILESTACK_HANDLE_BACKUP: ${{ secrets.FILESTACK_HANDLE_BACKUP }}
        envkey_THREADS_TO_IGNORE: ${{ secrets.THREADS_TO_IGNORE }}
        file_name: .env
        fail_on_empty: true
        sort_keys: false
    - name: Temporarily save dotenv file
      uses: actions/upload-artifact@v3
      with:
        path: .
        name: .env
        if-no-files-found: error
        retention-days: 1
    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.6.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install deps via poetry
      run: |
        poetry install --with=test && echo $(poetry show)
    - name: Run pytests
      run: poetry run pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Retrieve dotenv file
      uses: actions/download-artifact@v3
      with:
        name: .env
        if-no-files-found: error
    - name: Build image
      run: docker build -t "${DO_image}" .
    - name: Save Docker image
      run: docker save --output image.tar "${DO_image}"
    - name: Temporarily save Docker image
      uses: actions/upload-artifact@v3
      with:
        name: docker-artifact
        path: image.tar
        if-no-files-found: error
        retention-days: 1

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Retrieve saved Docker image
      uses: actions/download-artifact@v3
      with:
        name: docker-artifact
        if-no-files-found: error
    - name: Load Docker image
      run: docker load --input image.tar
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
    - name: Log into Digital Ocean Container Registry
      run: doctl registry login --expiry-seconds 600
    - name: Push image to Digital Ocean Container Registry
      run: docker push "${DO_image}"
