name: Mirror Bot CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.6.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install deps via poetry
      run: |
        poetry install --with=test && echo $(poetry show)
    - name: Run pytests
      run: poetry run pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Generate dotenv file
      uses: shine1594/secrets-to-env-action@master
      with:
        secrets: ${{ toJSON(secrets) }}
        secrets_env: production
    - name: Build image
      run: docker build -t registry.digitalocean.com/reddit-lemmy-mirror-bot/mirror-script:latest .
    - name: Temporarily save Docker image
      uses: actions/upload-artifact@v2
      with:
        name: docker-artifact
        path: tmp/artifacts
        retention-days: 1

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2'
    - name: Retrieve saved Docker image
      uses: actions/download-artifact@v2
      with:
        name: docker-artifact
        path: tmp/artifacts
    # - name: Generate dotenv file
    #   uses: shine1594/secrets-to-env-action@master
    #   with:
    #     secrets: ${{ toJSON(secrets) }}
    #     secrets_env: production
    # - name: Build image
    #   run: docker build -t registry.digitalocean.com/reddit-lemmy-mirror-bot/mirror-script:latest .
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
    - name: Log into Digital Ocean Container Registry
      run: doctl registry login --expiry-seconds 600
    - name: Push image to Digital Ocean Container Registry
      run: docker push registry.digitalocean.com/reddit-lemmy-mirror-bot/mirror-script:latest
